repository:
  name: zod-firebase-admin
  description: firebase-admin zod
  topics: zod, firebase, firebase-admin

  default_branch: main

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: true

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: '#cc0000'
    description: Something is broken
  - name: feature
    color: '#336699'
    description: New functionality
  - name: chore
    color: '#f2df8c'
    description: Repository or code maintenance
  - name: documentation
    color: '#6cb524'
    description: Change in the documentation
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies

teams:
  - name: developers
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - lint
          - type check
          - tests
          - markdown lint
          - commitlint
      enforce_admins: true
      required_linear_history: true
      required_signatures: true
      required_conversation_resolution: true
      restrictions:
        apps: []
        users: []
        teams: []
