name: Setup pnpm
description: Setup pnpm

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: sh
