name: Publish to NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: ./.github/workflows/actions/setup-pnpm

      - name: Publish to NPM
        run: npx lerna publish from-package --no-push --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
