name: Pull Request
on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: eslint
        run: pnpm eslint
      - name: prettier
        run: pnpm prettier
      - name: build (for publint)
        run: pnpm build
      - name: publint zod-firebase
        run: pnpm publint ./packages/zod-firebase
      - name: publint zod-firebase-admin
        run: pnpm publint ./packages/zod-firebase-admin

  type-check:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        zod: ['3', '4']
        firebase: ['11', '12']
        firebase_admin: ['12', '13']
        exclude:
          - firebase: '11'
            firebase_admin: '13'
          - firebase: '12'
            firebase_admin: '12'
    name: type check (zod@${{ matrix.zod }}, firebase@${{ matrix.firebase }}, firebase-admin@${{ matrix.firebase_admin }})
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install zod@^${{ matrix.zod }} at workspace root
        run: pnpm add -Dw zod@^${{ matrix.zod }}
      - name: Install firebase@^${{ matrix.firebase }} for zod-firebase
        run: pnpm -C packages/zod-firebase add -D firebase@^${{ matrix.firebase }}
      - name: Install firebase-admin@^${{ matrix.firebase_admin }} for zod-firebase-admin
        run: pnpm -C packages/zod-firebase-admin add -D firebase-admin@^${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: type-check
        run: pnpm run type-check

  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  markdown:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
