name: pull-request
on:
  pull_request:

jobs:
  lint:
    name: eslint & prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: eslint
        run: pnpm eslint
      - name: pettier
        run: pnpm prettier

  type-check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: type-check
        run: pnpm run type-check

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache firebase emulator
        uses: actions/cache@v4
        with:
          path: .cache/firebase
          key: ${{ runner.os }}-firebase-emulator

      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: tests
        run: pnpm test

      - name: Upload zod-firebase coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase/coverage
          flags: firebase
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase-admin/coverage
          flags: firebase-admin
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: integration tests
        run: npm run test:integration:ci

  markdown:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'
