name: Pull Request
on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: eslint
        run: pnpm eslint
      - name: prettier
        run: pnpm prettier
      - name: build (for publint)
        run: pnpm build
      - name: publint zod-firebase
        run: pnpm publint ./packages/zod-firebase
      - name: publint zod-firebase-admin
        run: pnpm publint ./packages/zod-firebase-admin

  type-check:
    name: type check
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        zod: ['zod@^3', 'zod@^4']
        firebase: ['firebase@^11', 'firebase@^12']
        firebase_admin: ['firebase-admin@^12', 'firebase-admin@^13']
        exclude:
          - firebase: 'firebase@^11'
            firebase_admin: 'firebase-admin@^13'
          - firebase: 'firebase@^12'
            firebase_admin: 'firebase-admin@^12'
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install Zod ${{ matrix.zod }} at workspace root
        run: pnpm add -Dw ${{ matrix.zod }}
      - name: Install Firebase ${{ matrix.firebase }} for zod-firebase
        run: pnpm -C packages/zod-firebase add -D ${{ matrix.firebase }}
      - name: Install Firebase Admin ${{ matrix.firebase_admin }} for zod-firebase-admin
        run: pnpm -C packages/zod-firebase-admin add -D ${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: type-check
        run: pnpm run type-check

  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  markdown:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
