name: Tests

on:
  workflow_call:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        zod: ['zod@^3', 'zod@^4']
        firebase: ['firebase@^11', 'firebase@^12']
        firebase_admin: ['firebase-admin@^12', 'firebase-admin@^13']
        exclude:
          - firebase: 'firebase@^11'
            firebase_admin: 'firebase-admin@^13'
          - firebase: 'firebase@^12'
            firebase_admin: 'firebase-admin@^12'
    steps:
      - uses: actions/checkout@v4
      - name: cache firebase emulator
        uses: actions/cache@v4
        with:
          path: .cache/firebase
          key: ${{ runner.os }}-firebase-emulator

      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install Zod ${{ matrix.zod }} at workspace root
        run: pnpm add -Dw ${{ matrix.zod }}
      - name: Install Firebase ${{ matrix.firebase }} for zod-firebase
        run: pnpm -C packages/zod-firebase add -D ${{ matrix.firebase }}
      - name: Install Firebase Admin ${{ matrix.firebase_admin }} for zod-firebase-admin
        run: pnpm -C packages/zod-firebase-admin add -D ${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: tests
        run: pnpm test

      - name: Upload zod-firebase coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase/coverage
          flags: firebase-${{ matrix.zod }}-${{ matrix.firebase }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase-admin/coverage
          flags: firebase-admin-${{ matrix.zod }}-${{ matrix.firebase_admin }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: integration tests
        run: npm run test:integration:ci
