name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        zod: ['3', '4']
        firebase: ['11', '12']
        firebase_admin: ['12', '13']
        exclude:
          - firebase: '11'
            firebase_admin: '13'
          - firebase: '12'
            firebase_admin: '12'
    name: tests (zod@${{ matrix.zod }}, firebase@${{ matrix.firebase }}, firebase-admin@${{ matrix.firebase_admin }})
    steps:
      - uses: actions/checkout@v4
      - name: cache firebase emulator
        uses: actions/cache@v4
        with:
          path: .cache/firebase
          key: ${{ runner.os }}-firebase-emulator

      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install zod@^${{ matrix.zod }} at workspace root
        run: pnpm add -Dw zod@^${{ matrix.zod }}
      - name: Install firebase@^${{ matrix.firebase }} for zod-firebase
        run: pnpm -C packages/zod-firebase add -D firebase@^${{ matrix.firebase }}
      - name: Install firebase-admin@^${{ matrix.firebase_admin }} for zod-firebase-admin
        run: pnpm -C packages/zod-firebase-admin add -D firebase-admin@^${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: tests
        run: pnpm test
      - name: Upload zod-firebase Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          directory: ./packages/zod-firebase/test-results
          flags: zod-${{ matrix.zod }}_firebase-${{ matrix.firebase }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          directory: ./packages/zod-firebase-admin/test-results
          flags: zod-${{ matrix.zod }}_firebase-admin-${{ matrix.firebase_admin }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload zod-firebase coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase/coverage
          flags: zod-${{ matrix.zod }}_firebase-${{ matrix.firebase }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase-admin/coverage
          flags: zod-${{ matrix.zod }}_firebase-admin-${{ matrix.firebase_admin }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: integration tests
        run: npm run test:integration:ci
